language: python
python:
  - "3.6"
install:
  - pip install coverage
script:
  - coverage run -m unittest
after_success:
  - bash < (curl -s https://codecov.io/bash)
branches:
  only:
    - master
    - dev
